version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=anamny_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  # From GitHub Secret
      - POSTGRES_DB=anamny_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  server:
    image: ghcr.io/hayshin/anamny-server:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}  # From GitHub Secret
      - SECRET_KEY=${SECRET_KEY}      # From GitHub Secret
      - GEMINI_API_KEY=${GEMINI_API_KEY}  # From GitHub Secret
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
