name: Simple Deploy Bl

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Digital Ocean
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        key: ${{ secrets.DO_SSH_KEY }}
        script: |
          # Set environment variables
          export GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}"
          export SECRET_KEY="${{ secrets.SECRET_KEY }}"
          export POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}"
          
          cd /opt/anamny 
          
          # Pull latest code and deploy
          git pull origin main
          docker compose -f docker-compose.prod.yml up -d --build
          
          # Run migrations
          docker compose -f docker-compose.prod.yml exec -T server alembic upgrade head
          
          echo "✅ Deployment complete!"

name: Test Secrets

on:
  workflow_dispatch  # Manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test DO_HOST
      run: |
        if [ -z "${{ secrets.DO_HOST }}" ]; then
          echo "❌ DO_HOST is empty"
          exit 1
        else
          echo "✅ DO_HOST is set"
        fi
    
    - name: Test SSH Connection
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        key: ${{ secrets.DO_SSH_KEY }}
        script: |
          echo "✅ SSH connection successful!"
          pwd
