name: Debug Secrets

on:
  push:
    branches: [ master ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Check secrets
      run: |
        echo "DO_HOST exists: ${{ prod.secrets.DO_HOST != '' }}"
        echo "DO_USERNAME exists: ${{ prod.secrets.DO_USERNAME != '' }}"
        echo "DO_SSH_KEY exists: ${{ prod.secrets.DO_SSH_KEY != '' }}"